// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://odmagicmuoxjnoxtowrs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kbWFnaWNtdW94am5veHRvd3JzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0NDM4NjcsImV4cCI6MjA3MzAxOTg2N30.i4_p6g1GxB_FP74tMDWFGYCuvXt7GKh_UsmnIaj4MNI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});